name: Coverage

on:
  push:
    branches: [ master, upgrade ]
    paths:
      - 'accessors-smart/**'
      - 'json-smart/**'
      - '.github/workflows/coverage.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'accessors-smart/**'
      - 'json-smart/**'
      - '.github/workflows/coverage.yml'

permissions:
  contents: read

jobs:
  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: 11
        distribution: 'temurin'
        cache: 'maven'

    - name: Build and test accessors-smart with coverage
      run: cd accessors-smart && ./mvnw -q clean install

    - name: Build and test json-smart with coverage
      run: cd json-smart && ./mvnw -q clean test

    - name: Upload accessors-smart coverage to Coveralls
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        file: accessors-smart/target/site/jacoco/jacoco.xml
        format: jacoco
        flag-name: accessors-smart
        parallel: true

    - name: Upload json-smart coverage to Coveralls
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        file: json-smart/target/site/jacoco/jacoco.xml
        format: jacoco
        flag-name: json-smart
        parallel: true

    - name: Finish parallel build
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: true