
name: json smart formatting
on:
  push:
    branches:
      - master
      - upgrade
    paths:
      - 'accessors-smart/**'
      - 'json-smart/**'
      - 'json-smart-action/**'
      - '.github/workflows/json-smart-formatting.yml'
  pull_request:
    branches:
      - master
    paths:
      - 'accessors-smart/**'
      - 'json-smart/**'
      - 'json-smart-action/**'
      - '.github/workflows/json-smart-formatting.yml'

permissions:
  contents: read

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'maven'
          
      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
          
      - name: Check formatting accessors-smart
        run: cd accessors-smart; ./mvnw spotless:check

      - name: Check formatting json-smart
        run: cd json-smart; ./mvnw spotless:check

      - name: Check formatting json-smart-action
        run: cd json-smart-action; ./mvnw spotless:check
